#!/usr/bin/perl -w
###APPNAME:     bbs-click
###APPAUTHOR:   duel
###APPDATE:	2009-01-24 08:02:37
###APPVER:	0.1
###APPDESC:     bbs-click	
###APPUSAGE:	
###APPEXAMPLE:	bbs-click
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty/;
exit 0 if(help_required($0,@ARGV));
#exit 0 if(help_even_empty($0,@ARGV));

my ($url,$user,$proxy) = @ARGV;
die("Empty url\n") unless($url);
$user="keyduel" unless($user);
$url .= "?" unless($url =~ /\?/);
$url .= "fromuser=keyduel" unless($url =~ /(fromuser|fromuid)/);
print STDERR "click... [$url] using [$proxy]\n";
exit system("proxy-test",$url,$proxy);




