#!/usr/bin/perl -w
###APPNAME:     bbs-flash
###APPAUTHOR:   duel
###APPDATE:	2009-01-24 08:10:52
###APPVER:	0.1
###APPDESC:     bbs-flash	
###APPUSAGE:	
###APPEXAMPLE:	bbs-flash
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty/;
exit 0 if(help_required($0,@ARGV));
#exit 0 if(help_even_empty($0,@ARGV));

my @bbs;
while(<>) {
    chomp;
    push @bbs,"$_";
}

my @proxy_page = qw(
    http://www.proxycn.com/html_proxy/30fastproxy-1.html
);
my @proxy;

foreach(@proxy_page) {
    open FI,"-|","netcat '$_' | parse_proxycn";
    while(<FI>) {
        chomp;
        push @proxy,$_;
    }
}
print STDERR "BBS:[" . $#bbs . "]\tPROXY:[" . $#proxy . "]\n";
foreach my $proxy (@proxy) {
    foreach my $bbs(@bbs) {
        system("bbs-click",$bbs,"keyduel",$proxy);
    }
}
