#!/usr/bin/perl
###APPNAME:     book_download.pl
###APPAUTHOR:   xiaoranzzz
###APPDATE:	Tue Mar 11 04:58:02 2008
###APPVER:	0.1
###APPDESC:     download html using book_parser
###APPUSAGE:    indexURL [directory]	
###APPEXAMPLE:	book_download http://book.sina.com.cn/nzt/lit/wodemingzijiaohong/index.shtml src
use strict;
use XML::Simple;
use Data::Dumper;
$ARGV[0]="-h" unless(@ARGV);
foreach(@ARGV){
    exit(system("plhelp",$0,@ARGV)) if($_ eq "-h" || $_ eq "--help");
}

sub buildURL($$) {
    my $base=shift;
    my $href=shift;
    return "$base\/$href" if($href =~ /^[^\/]/);
    $base =~ s/(http:\/\/[^\/]*)\/.*$/\1/;
    return "$base$href";
}

my $url=shift;
my $saveto=shift;
open FI,"-|","book_parser '$url'";
my $data = join("",<FI>);
my $book = XMLin($data,SuppressEmpty=>1,NoAttr=>1,KeyAttr=>[]);
close FI;

my $base = $url;
$base =~ s/\/[^\/]*$//g;
my $name = $url;
$name =~ s/\/$//g;
$name =~ s/^.*\///g;


#print Dumper($book);
$book->{title}=$name unless($book->{title});

if(!$saveto) {
    if($book->{author}) {
        $saveto=$book->{author} . "/" . $book->{title};
        if(! -d $book->{author}) {mkdir $book->{author} or die("$!\n");}
    }
    else {
        $saveto=$book->{title};
    }
    if(! -d $saveto) {mkdir $saveto or die("$!\n");}
    $saveto .= "/src";
}

if(! -d $saveto) {
    mkdir $saveto or die("$!\n");
}
chdir $saveto;

open fO,">","bookinfo.xml";
print fO $data;
close fO;

open fO,"|-","batchget -n '$book->{title}' -r '$url'";
print fO $url,"\n";
if($book->{pages}) {
    for(my $i=0;$i<@{$book->{pages}};$i++) {
        print fO buildURL($base,$book->{pages}->[$i]->{url}),"\n";
    }
}
close fO;
print STDERR "Task done! Saved in $saveto\n";


