#!/usr/bin/perl -w
###APPNAME:     color_print_wine
###APPAUTHOR:   duel
###APPDATE:	2009-02-27 16:02:02
###APPVER:	0.1
###APPDESC:     color_print_wine	
###APPUSAGE:	
###APPEXAMPLE:	color_print_wine
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty/;
exit 0 if(help_required($0,@ARGV));
#exit 0 if(help_even_empty($0,@ARGV));
use Term::ANSIColor;

my $f=color("yellow");
my $k=color("cyan");
my $r=color("reset");
while(<>) {
    s/(['"])([^\1]+)\1/$1$f$2$r$1/g;
    s/(\w*(:?native|builtin)\w*)/$k$1$r/g;
    print STDERR $_;
}
