#!/usr/bin/perl -w
###APPNAME:     discuz_dump
###APPAUTHOR:   duel
###APPDATE:	2009-01-16 15:20:25
###APPVER:	0.1
###APPDESC:     discuz_dump	
###APPUSAGE:	
###APPEXAMPLE:	discuz_dump
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty/;
exit 0 if(help_required($0,@ARGV));
#exit 0 if(help_even_empty($0,@ARGV));

use MyPlace::Discuz;
my ($url,$user,$pass,$what) = @ARGV;
$user ||= "keyduel";
$pass ||= "absfreedom";
my $index = MyPlace::Discuz->new(user=>$user,pass=>$pass);
$index->init_with_url($url);
binmode STDERR,"utf8";
use Data::Dumper;die Dumper($what ? $index->{$what} : $index),"\n";

