#!/usr/bin/perl -w
###APPNAME:     diskimg-fstype
###APPAUTHOR:   root
###APPDATE:	Sun Oct  7 01:36:57 2007
###APPVER:	0.1
###APPDESC:     check fstype for  partition  of disk image.	
###APPUSAGE:	(disk image file) (partition NUM)
###APPEXAMPLE:	diskimg-fstype disk.img 1
###APPOPTION:	
use strict;
$ARGV[0]="-h" unless(@ARGV);
foreach(@ARGV){
    exit(system("plhelp",$0,@ARGV)) if($_ eq "-h" || $_ eq "--help");
}
my $disk=shift;
my $num=shift;

die("File not exists\n") unless(-f $disk);
$num=1 unless($num);

my $name=$disk;

my %fstype=(
    "1"=>"vfat",
    "83"=>"ext2",
    "82"=>"swap",
    "4"=>"msdos",
    "5"=>"",
    "6"=>"msdos",
    "b"=>"vfat",
    "c"=>"vfat",
);

open(TABLE,"/sbin/fdisk -ul $disk 2>/dev/null |") or die("$!\n");

while(<TABLE>) {
    if(m{$name$num\s+\*?\s+(\d+)\s+(\d+)\s+(\d+)\s+([a-z0-9]+)\s+([a-zA-z0-9]+)$}) {
        print $fstype{$4};
        last;
    }
}
close TABLE;


