#!/usr/bin/perl -w
###APPNAME:     epubmake
###APPAUTHOR:   xiaoranzzz
###APPDATE:	Wed Apr 28 00:34:14 2010
###APPVER:	0.1
###APPDESC:     epubmake	
###APPUSAGE:	
###APPEXAMPLE:	epubmake
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty/;
#exit 0 if(help_required($0,@ARGV));
exit 0 if(help_even_empty($0,@ARGV));

use Cwd;

my $cwd=getcwd();

foreach(@ARGV) {
    if(-d $_) {
        my $bookname = $_;
        $bookname =~ s/^.*[\/\\]//;
        $bookname =~ s/[\/\\]+$//;
        chdir $_ or die("$!\n");
        print STDERR "$bookname.epub ... \n";
        if(-f "$cwd/$bookname.epub") {
            print STDERR "Delete $bookname.epub first...\n";
            unlink "$cwd/$bookname.epub";
        }
        die("$!\n") unless(system("zip","-rXDq","$cwd/$bookname.epub","mimetype",".")==0);
#        die("$!\n") unless(system("zip","-rXDv","$cwd/$bookname.epub",".")==0);
        print STDERR "\"$cwd/$bookname.epub\" created.\n";
        chdir $cwd or die("$!\n");
        
    }
    else {
        print STDERR "Directory:\"$_\" not exist!\n";
    }
}
