#!/usr/bin/perl -w
use strict;

use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty/;
#exit 0 if(help_required($0,@ARGV));
exit 0 if(help_even_empty($0,@ARGV));


my $html_index = shift;
die("Usage:$0 html_index_file\n") unless($html_index);

use MyPlace::Epub qw/get_file_id get_media_type/;
my @URLEXP = (
            '"([^"]+\.(?:html|xhtml|xml|htm))"',
            '\'([%\']+\.(?:html|xhtml|xml|htm))\'',
            '=\s*([^\s]+\.(?:html|xhtml|xml|htm))',
);

sub print_spine {
    my $file = shift;
    return undef unless($file);
    my $id = get_file_id($file);
    return undef unless($id);
    print '<itemref linear="yes" idref="'. $id . '" linear="yes"/>' . "\n";
}

sub get_spine {
    my $FI = shift;
    while(<$FI>) {
        foreach my $exp (@URLEXP) {
            my @match = $_ =~ m/$exp/ig;
            if(@match) {
                print_spine($_) foreach(@match);
                last;
            }
        }
    }
}

if($html_index eq '-') {
   get_spine(\*STDIN);
}
else {
    my $FI;
    open $FI,"<",$html_index or die("$!\n");
    get_spine($FI);
    close $FI;
}




