#!/usr/bin/perl -w
###APPNAME:     epub_manifest_add
###APPAUTHOR:   xiaoranzzz
###APPDATE:	Wed Apr 28 01:12:41 2010
###APPVER:	0.1
###APPDESC:     epub_manifest_add	
###APPUSAGE:	
###APPEXAMPLE:	epub_manifest_add
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty/;
exit 0 if(help_required($0,@ARGV));
#exit 0 if(help_even_empty($0,@ARGV));

use File::Glob qw/bsd_glob/;
use MyPlace::Epub qw/get_media_type get_file_id/;


sub print_item {
    my $item=shift;
    my $id = get_file_id($item);
    my $type = get_media_type($item);
    if($type) {
            print "<item id=\"$id\" href=\"$item\" media-type=\"$type\"/>\n";
    }
}

sub get_item {
    my $path = shift;
    my $glob_exp;
    my @result;
    if($path) {
        $glob_exp = "$path/*";
    }
    else {
        $glob_exp = "*";
    }
    foreach my $filename (bsd_glob($glob_exp)) {
        if(-d $filename) {
            push @result,&get_item($filename);
        }
        elsif(-f $filename) {
            push @result,$filename;
        }
    }
    return @result;
}

if(@ARGV) {
    foreach my $path (@ARGV) {
        print_item($_) foreach(get_item($path));
    }
}
else {
    print_item($_) foreach(get_item());
}


