#!/usr/bin/perl -w
###APPNAME:     firefox-set-proxy
###APPAUTHOR:   duel
###APPDATE:	2009-01-24 02:39:54
###APPVER:	0.1
###APPDESC:     firefox-set-proxy	
###APPUSAGE:    [output]	
###APPEXAMPLE:	firefox-set-proxy
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};
use MyPlace::Script::Usage qw/help_required help_even_empty/;
exit 0 if(help_required($0,@ARGV));
#exit 0 if(help_even_empty($0,@ARGV));

my $output=shift;
$output ||="";
exec("pac-from-proxycn",$output,"http://www.google.com");

