#!/usr/bin/perl -w
###APPNAME:     googleImage.pl
###APPAUTHOR:   duel
###APPDATE:	2009-08-25 04:22:53
###APPVER:	0.1
###APPDESC:     googleImage.pl	
###APPUSAGE:	
###APPEXAMPLE:	googleImage.pl
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};
use URI::Escape;
use MyPlace::Script::Usage qw/help_required help_even_empty/;
#exit 0 if(help_required($0,@ARGV));
exit 0 if(help_even_empty($0,@ARGV));

my ($key,$from,$to) = @ARGV;
$from = 1 unless($from);
$to = 1 unless($to);
$key = uri_escape($key);


foreach my $page ($from .. $to) {
    my $start = ($page -1) * 20;
    my $url = 'http://images.google.com/images?safe=off&um=1&newwindow=1&sa=1&aq=f&oq=&imgsz=l' . "&q=$key&start=$start";

    open FI,"-|","wget",qw{-O - -e robots=off -U Mozilla/5.0},$url or die("$!\n");
    while(<FI>) {
        my @match = $_ =~ m/imgurl\\x3d(.*?)\\x26/g;
        print $_,"\n" foreach(@match);
    }
    close FI;
}





