#!/usr/bin/perl -w
# $Id$
use strict;
require v5.8.0;
our $VERSION = 'v0.1';

my $idx = 1;
my $total = 2;

print "[$idx/$total] git commit ", (@ARGV ? join(" ",@ARGV) : ""), "\n";
my $NEED_COMMIT = `git diff`;
chomp($NEED_COMMIT);
if($NEED_COMMIT) {
    if (system(qw/git commit/,@ARGV) != 0) {
        die "[$idx/$total] git commit failed\n";
    }
}
else {
    system(qw/git commit/,@ARGV);
}
$idx++;
print "[$idx/$total] git svn dcommit\n";
if(system(qw/git svn dcommit/) != 0) {
    die "[$idx/$total] git svn dcommit failed\n";
}
exit 0;


__END__

=pod

=head1  NAME

git-svn-commit - PERL script

=head1  SYNOPSIS

git-svn-commit [options] ...

=head1  OPTIONS

=over 12

=item B<--version>

Print version infomation.

=item B<-h>,B<--help>

Print a brief help message and exits.

=item B<--manual>,B<--man>

View application manual

=item B<--edit-me>

Invoke 'editor' against the source

=back

=head1  DESCRIPTION

___DESC___

=head1  CHANGELOG

    2010-10-31  xiaoranzzz  <xiaoranzzz@myplace.hell>
        
        * file created.

=head1  AUTHOR

xiaoranzzz <xiaoranzzz@myplace.hell>

=cut

#       vim:filetype=perl
