#!/usr/bin/perl -w
use Cwd qw/getcwd/;
use File::Glob qw/bsd_glob/;
use strict;
use version '5.8';

sub run {
	print STDERR join(" ",@_),"\n";
	return system(@_)==0;
}
sub glob_git {
    my $opt = shift; 
    my $dir = shift;
    if($opt eq '-l') {
    }
    else {
        $dir = $opt;
        return if(-l $dir);
    }
 #   print STDERR "glob in $dir\n";
    my @gits;
    foreach(bsd_glob("$dir/.*"),bsd_glob("$dir/*")) {
        if(m/(?:^|[\/\\])\.+$/) {
            next;
        }
        elsif(-d $_) {
            if(m/\.git$/) {
                push @gits,$_;
            }
            else {
                my @r_git = &glob_git($_);
                push @gits,@r_git if(@r_git);
            }
        }
    }
    return @gits;
}
sub tee {
    my $HD = shift;
    print STDERR @_;
    print $HD @_;
}
sub t_run {
    my $fh = shift;
    tee($fh,join(" ",@_),"\n");
    open FI,"-|",@_;
    tee($fh,$_) while(<FI>);
    close FI;
}
sub pack_bundle {
	my $project = shift;
	$project =~ s/\/+$//;
    my $name = $project;
    my $cwd = getcwd();
    my $parent = $cwd;
	if($project =~ m/^(.+)\/([^\/]+)$/) {
        $name = $2;
        $parent = $1;
    }
    
    open my $FTEE,">","$name.log";
    chdir $project;
    my @gits = glob_git("-l",".");
    my @repos;
    foreach(@gits) {
        s/^.[\/\\]+//;
        my $repo = {rel=>$_};
        $repo->{abs}="$project/$_";
        $repo->{tree}= $repo->{abs};
        $repo->{tree} =~ s/\.git$//;
        push @repos,$repo;
    }

    &tee($FTEE,scalar(localtime),"\nStart packing bundle from [$project] as [$name]\n");
    &tee($FTEE,'=' x 79,"\n");
    &tee($FTEE,"Found git databases in $project:\n",join("\n",map {$_->{abs}} @repos),"\n");
    foreach my $repo (@repos) {
        &tee($FTEE,"Updating repository $repo->{abs} ...\n");
        my @git_cmd = ("git","--git-dir",$repo->{abs},"--work-tree",$repo->{tree});
#        run(@git_cmd,"status");
#        run(@git_cmd,"branch","-av");
        t_run($FTEE,@git_cmd,"svn","fetch");
        t_run($FTEE,@git_cmd,"fetch","--all");
        t_run($FTEE,@git_cmd,"log","--oneline","-n",5);
        t_run($FTEE,@git_cmd,"gc");
    }
    &tee($FTEE,"Packing $project as $cwd/$name.tar\n"); 
    t_run($FTEE,"tar","-cvf","$cwd/$name.tar",map {$_->{rel}} @repos);
    &tee($FTEE,'=' x 79,"\n");
    &tee($FTEE,scalar(localtime),"\nFinished packing bundle from [$project] as [$name]\n");
    close $FTEE;
    chdir $cwd;
}
my $action = shift;
if($action eq 'pack') {
    open my $LOG,">>gsvn-bundle.log";
    foreach(@ARGV) {
        tee($LOG,scalar(localtime),": packing bundle from $_\n");
        pack_bundle($_) foreach(@ARGV);
    }
    close $LOG;
}


