#!/usr/bin/perl -w
# $Id$
use strict;
require v5.10.0;
our $VERSION = 'v0.1';
print "[1/2] git commit ", (@ARGV ? join(" ",@ARGV) : ""), "\n";
if (system(qw/git commit/,@ARGV) == 0) {
    print "[2/2] git svn dcommit\n";
    if(system(qw/git svn dcommit/) == 0) {
        exit 0;
    }
    else {
        print "[2/2] git svn dcommit failed\n";
        exit 2;
    }
}
else {
    print "[1/2] git commit failed","\n";
    exit 1;
}



__END__

=pod

=head1  NAME

git-svn-commit - PERL script

=head1  SYNOPSIS

git-svn-commit [options] ...

=head1  OPTIONS

=over 12

=item B<--version>

Print version infomation.

=item B<-h>,B<--help>

Print a brief help message and exits.

=item B<--manual>,B<--man>

View application manual

=item B<--edit-me>

Invoke 'editor' against the source

=back

=head1  DESCRIPTION

___DESC___

=head1  CHANGELOG

    2010-10-31  xiaoranzzz  <xiaoranzzz@myplace.hell>
        
        * file created.

=head1  AUTHOR

xiaoranzzz <xiaoranzzz@myplace.hell>

=cut

#       vim:filetype=perl
