#!/usr/bin/perl -w
###APPNAME:     htmlconv_foldername
###APPAUTHOR:   duel
###APPDATE:	2009-04-17 01:08:39
###APPVER:	0.1
###APPDESC:     htmlconv_foldername	
###APPUSAGE:	
###APPEXAMPLE:	htmlconv_foldername
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty/;
exit 0 if(help_required($0,@ARGV));
#exit 0 if(help_even_empty($0,@ARGV));

my $exp="";
while(@ARGV) {
    my $from=shift;
    my $to=shift;
    last unless($from and $to);
    $exp = $exp . 's#' . $from . '[\\\/]#' . $to . '\/#g;';
}
die("Nothing to do!\n") unless($exp);

my @files;
while(<STDIN>) {
    chomp;
    push @files,$_;
}
my @cmd = ("sed","-i","-e",$exp,@files);
exec @cmd;
#print STDERR @cmd;


