#!/usr/bin/perl -w
###APPNAME:     html2unix
###APPAUTHOR:   xiaoranzzz
###APPDATE:	Wed Apr 28 02:26:38 2010
###APPVER:	0.1
###APPDESC:     html2unix convert \"href\" \"src\" to lowercase
###APPUSAGE:	
###APPEXAMPLE:	html2unix
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty/;
#exit 0 if(help_required($0,@ARGV));
exit 0 if(help_even_empty($0,@ARGV));
use HTML::TreeBuilder;


sub lc_links {
    my $tree = shift;
    foreach my $attr (qw/src href/) {
        my @elms = $tree->look_down($attr,qr/./);
        map {$_->attr($attr,lc($_->attr($attr)))} @elms;
    }
    return $tree;
}

foreach my $file (@ARGV) {
    if($file eq '-') {
        my $tree = HTML::TreeBuilder->new_from_content(<STDIN>);
        lc_links($tree);
        print FO $tree->as_HTML();
        $tree->delete();
    }
    elsif(-f $file and $file =~ m/\.(?:html|htm|xml|xhtml)$/) {
        print STDERR "Converting $file...";
        my $tree = HTML::TreeBuilder->new_from_file($file);
        lc_links($tree);
        open FO,">".$file or die("$!\n");
        print FO $tree->as_HTML();
        close FO;
        $tree->delete();
        print STDERR "\t [OK]\n";
    }
    else {
        print STDERR "\"$file\" Ingored.\n";
    }
}






