#!/usr/bin/perl -w
###APPNAME:     makeclip
###APPAUTHOR:   duel
###APPDATE:	2008-04-29 07:56:16
###APPVER:	0.1
###APPDESC:     makeclip	
###APPUSAGE:	(file name) (start) (length) [clip_name] [profile]
###APPEXAMPLE:	makeclip input.avi 00:00 00:20 wmv
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty format_help/;
exit 0 if(help_even_empty($0,@ARGV));


my $input=shift;
my $start=shift;
my $length=shift;
my $clip_name=shift;
my $profile=shift;

die("File not exists:$input\n") unless(-f $input);
$profile="avi" unless($profile);


require MyPlace::Filename;
my $ext;
$ext = $profile if($profile =~ m/^(?:avi|mpeg|mp4|rmvb|mkv)$/);
$ext = 'mp4' if($profile =~ m/^(?:milestone|ms)$/i);
$ext = MyPlace::Filename::get_extname($input) unless($ext);
$ext =~ s/^\.+//;
my $basename=MyPlace::Filename::get_basename($input);
unless($clip_name) {
    my $idx=1;
    while(-f "$basename-clip$idx.$ext") {
        $idx++;
    }
    $clip_name = "clip$idx";
}
my $output="$basename-$clip_name.$ext";

my $encoder="ffmpeg";
unless(`which "$encoder"`) {
    $encoder = 'mencoder';
}
die("Both encoder \"ffmpeg\" and \"mencoder\" not installed!\n") unless(`which "$encoder"`);

#my $comment=`date +%x`;
#chomp($comment);

sub fix_time_arg {
    my $time = shift;
    $time = '0:0:0:' . $time;
    $time =~ s/^.+(\d+:\d+:\d+)$/$1/;
    return $time;
}

my @enarg;
push @enarg,'-ss',fix_time_arg($start) if($start);
$encoder = 'mencoder' if($profile =~ m/^avi$/i);
if($encoder eq 'ffmpeg') {
    push @enarg,'-t',fix_time_arg($length) if($length);
    push @enarg,'-i',$input;
	push @enarg,'-q','1';
    if($profile =~ m/^(?:3gp|mp4)$/i) {
        push @enarg,'-s','320x240','-vf','scale=-1:-1';
    }
    elsif($profile =~ m/^(?:milestone|ms)$/i) {
        push @enarg,'-s','428x240','-vf','scale=-1:-1';
    }
	elsif($profile =~ m/^(\d+)%$/) {
		push @enarg,'-vf',"scale=$1/100*iw:$1/100*ih";
	}
	elsif($profile =~ m/^(\d+)[xX](\d+)$/) {
		push @enarg,'-s',"$1x$2",'-vf','scale=-1:-1';
	}
    push @enarg,@ARGV if(@ARGV);
    push @enarg,$output;
}
else {
    push @enarg,$input;
    push @enarg,'-endpos',fix_time_arg($length) if($length);
    push @enarg,'-profile',$profile if($profile);
    push @enarg,'-o',$output;
    push @enarg,@ARGV if(@ARGV);
}

open FO,">>","makeclip.log";
print FO "makeclip $input $start $length $clip_name $profile", @ARGV ? @ARGV : "","\n";
print FO $encoder," \"",join("\" \"",@enarg),"\"\n";
print STDERR $encoder," \"",join("\" \"",@enarg),"\"\n";
close FO;

print STDERR join(" ",($encoder,@enarg)),"\n";
exec $encoder,@enarg;



