#!/usr/bin/perl -w
###APPNAME:     makeclip
###APPAUTHOR:   duel
###APPDATE:	2008-04-29 07:56:16
###APPVER:	0.1
###APPDESC:     makeclip	
###APPUSAGE:	(file name) (start) (length) [profile]
###APPEXAMPLE:	makeclip input.avi 00:00 00:20 wmv
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty format_help/;
exit 0 if(help_even_empty($0,@ARGV));


my $input=shift;
my $start=shift;
my $length=shift;
my $profile=shift;

die("File not exists:$input\n") unless(-f $input);
$profile="avi" unless($profile);

require MyPlace::Filename;
my $basename=MyPlace::Filename::get_basename($input);
my $idx=1;
while(-f "$basename-clip$idx.$profile") {
    $idx++;
}
my $output="$basename-clip$idx.$profile";

my $encoder="mencoder";
die("\"$encoder\" not installed!\n") unless(`which "$encoder"`);

my $comment=`date +%x`;
chomp($comment);

my @enarg;
push @enarg,$input,"-o","$output","-profile",$profile,"-info","name=$basename:comment=$comment:artist=$ENV{USER}";
push @enarg,"-ss",$start if($start);
push @enarg,"-endpos",$length if($length);


open FO,">>","makeclip.log";
print FO $encoder," \"",join("\" \"",@enarg),"\"\n";
print STDERR $encoder," \"",join("\" \"",@enarg),"\"\n";
close FO;

exec $encoder,@enarg;



