#!/usr/bin/perl -w
###APPNAME:     mplayer-make-screenshot
###APPAUTHOR:   duel
###APPDATE:	2008-05-11 02:53:08
###APPVER:	0.1
###APPDESC:     mplayer-make-screenshot	
###APPUSAGE:	filename [number of screenshots]
###APPEXAMPLE:	mplayer-make-screenshot [--hand] movie.avi 100
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty/;
exit 0 if(help_even_empty($0,@ARGV));

my $hand=shift;
if($hand eq "--hand") {
    $hand=1;
}
else {
    unshift @ARGV,$hand;
    $hand=0;
}

my $fn=shift;
die "File not exist: $fn" unless(-r $fn);


sub dup_line {
    my $line=shift;
    print STDERR "$line\n";
    return "$line\n";
}

#my @player_opt=("-slave","-vf","screenshot","-framedrop","-vo","jpeg:quality=100:smooth=100");
my @player_opt= $hand ? ("-vf","screenshot","-framedrop") : ("-slave","-vf","screenshot","-framedrop") ;
my $pipe_broken=0;

sub on_exit() {
    $pipe_broken=1;
    exit 0 unless(system("which png2jpg 1>/dev/null")==0);
    my @pngs=glob("*.png");
    if(@pngs) {
        system("png2jpg",@pngs);
        system("rm","-v",@pngs);
    }
    exit 0;
}

$SIG{PIPE}="on_exit";

if($hand) {
    system("mplayer",@player_opt,$fn);
}
else {
my $num=shift;
$num = 50 unless($num>0);
my $step=0;
$step = 100.00 / $num;
my $total=0;
my $shot_cmd = "screenshot";
my $seek_cmd = "seek ";
open FO,"|-","mplayer",@player_opt,$fn;
select ((select(FO), $| = 1)[0]);
select ((select(STDERR), $| = 1)[0]);
sleep 5;
print FO dup_line("pause");
print FO dup_line($seek_cmd . "4 0");
print FO dup_line($shot_cmd);
until($total>=99.88) {
    $total += $step;
    $total=99.88 if($total>99.88);
    sleep 2;
    print FO dup_line($seek_cmd . "$total% 1") or last;
    sleep 2;
    print FO dup_line($shot_cmd);
}
print FO dup_line("quit");
close FO;
}

on_exit unless($pipe_broken); 
