#!/usr/bin/perl -w
###APPNAME:     mv_tag
###APPAUTHOR:   duel
###APPDATE:	2009-03-17 15:42:19
###APPVER:	0.1
###APPDESC:     mv_tag	
###APPUSAGE:	
###APPEXAMPLE:	mv_tag
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty/;
exit 0 if(help_even_empty($0,@ARGV));

#my $date=`date -- '+%F'`;chomp($date);
my $date="";
my $tags=shift;
my @files=@ARGV;

foreach(@files) {
    if($_ =~ m/\*/) {
        foreach my $filename(glob($_)) {
            my $basename = $filename;
            $basename =~ s/#.*#//;
            system("mv","-v","--",$_,"#$tags#$basename");
        }
    }
    else {
        my $basename = $_;
        $basename =~ s/#.*#//;
        system("mv","-v","--",$_,"#$tags#$basename");
    }
}
exit 0;


