#!/usr/bin/perl -w
###APPNAME:     netcat
###APPAUTHOR:   duel
###APPDATE:	2009-01-06 17:32:15
###APPVER:	0.1
###APPDESC:     netcat a http url with autologin support
###APPUSAGE:	(url)
###APPEXAMPLE:	netcat www.google.com
use strict;
die("Usage:$0 URL\n") unless(@ARGV);

my $verbose = 0; 
my $url = shift;
if($url eq '-v') {
	$url = shift;
	$verbose = 1;
}
$url = "http://$url" unless($url =~ /^(http|https|ftp):/i);

use MyPlace::LWP;
print STDERR "$url " if($verbose);
my($ok,$data,$res) = (new MyPlace::LWP('progress'=>$verbose))->get($url,@ARGV);
if($ok) {
	print $data;
	exit 0;
}
else {
	print STDERR "[",$res->code,"]",$res->status_line,"\n" unless($ok);
	exit $res->code;
}

__END__

use LWP::UserAgent;
use HTTP::Cookies;


my  $ua = LWP::UserAgent->new;
my $cookie = HTTP::Cookies->new(file => "$ENV{'HOME'}/.lwp_cookies.dat", autosave => 1);
$ua->cookie_jar($cookie);
$ua->agent("Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.3) Gecko/2008092416 Firefox/3.0.3 Firefox/3.0.1");
my $req = HTTP::Request->new(GET => $url);
my $res = $ua->request($req);
  if ($res->is_success) {
      print $res->content;
  }
  else {
      print STDERR $res->status_line, "\n";
      exit 1;
  }
exit 0;

