#!/usr/bin/perl -w
###APPNAME:     netcat
###APPAUTHOR:   duel
###APPDATE:	2009-01-06 17:32:15
###APPVER:	0.1
###APPDESC:     netcat a http url with autologin support
###APPUSAGE:	(url)
###APPEXAMPLE:	netcat www.google.com
use strict;
use MyPlace::Curl;
my %ua = (
	'android'=>'Mozilla/5.0 (Android 9.0; Mobile; rv:61.0) Gecko/61.0 Firefox/61.0',
	'firefox'=>'Mozilla/5.0 (Windows NT 6.1; rv,2.0.1) Gecko/20100101 Firefox/4.0.1',
	'ie'=>'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0;',
	'chrome'=>'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_0) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11',
	'iphone'=>'Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_3 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5',
);
my $cookie = $ENV{HOME} . "/.curl_cookies.dat";
my $p = MyPlace::Curl->new(
	"location"=>'',
	"silent"=>'',
	"show-error"=>'',
	"cookie"=>$cookie,
	"max-time"=>120,
);
my @args;
my $ua;
while(@ARGV) {
	my $a = shift(@ARGV);
	if($a =~ m/^(?:--user-agent|--useragent|--ua|-u)$/) {
		$ua = shift(@ARGV);
	}
	else {
		push @args,$a;
	}
}
if($ua) {
	$ua = 'firefox' unless($ua{$ua});
	push @args,"--user-agent",$ua{$ua};
}
print STDERR "curl " . join(" ",@args),"\n";
my($exit,$data) = $p->get(@args);
if($exit == 0) {
	print $data,"\n";
	exit 0;
}
else {
	print STDERR "Error: $data\n";
	exit $exit;
}

__END__

die("Usage:$0 URL\n") unless(@ARGV);

my $verbose = 0; 
my $url = shift;
if($url eq '-v') {
	$url = shift;
	$verbose = 1;
}
$url = "http://$url" unless($url =~ /^(http|https|ftp):/i);

use MyPlace::LWP;
print STDERR "$url " if($verbose);
my($ok,$data,$res) = (new MyPlace::LWP('progress'=>$verbose))->get($url,@ARGV);
if($ok) {
	print $data;
	exit 0;
}
else {
	print STDERR "[",$res->code,"]",$res->status_line,"\n" unless($ok);
	exit $res->code;
}

__END__

use LWP::UserAgent;
use HTTP::Cookies;


my  $ua = LWP::UserAgent->new;
my $cookie = HTTP::Cookies->new(file => "$ENV{'HOME'}/.lwp_cookies.dat", autosave => 1);
$ua->cookie_jar($cookie);
$ua->agent("Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.3) Gecko/2008092416 Firefox/3.0.3 Firefox/3.0.1");
my $req = HTTP::Request->new(GET => $url);
my $res = $ua->request($req);
  if ($res->is_success) {
      print $res->content;
  }
  else {
      print STDERR $res->status_line, "\n";
      exit 1;
  }
exit 0;

