#!/usr/bin/perl -w
# $Id$
package MyPlace::Script::ntfs_junction;
use strict;
use Cwd qw/getcwd/;
use File::Spec::Functions qw/catdir catfile/;
my $UTF8;
our $VERSION = 'v0.1';
my @OPTIONS = qw/
	help|h|? 
	manual|man
	target|t=s
	junction|j
	symbold|d
	symbol|s
/;
my %OPTS;
if(@ARGV)
{
    require Getopt::Long;
    Getopt::Long::GetOptions(\%OPTS,@OPTIONS);
}
else {
	$OPTS{'help'} = 1;
}
if($OPTS{'help'} or $OPTS{'manual'}) {
	require Pod::Usage;
	my $v = $OPTS{'help'} ? 1 : 2;
	Pod::Usage::pod2usage(-exitval=>$v,-verbose=>$v);
    exit $v;
}

sub run {
	return unless(@_);
	my $BOUT = *STDOUT;
	open STDOUT,"<","/dev/null";
	close STDOUT;
	my $r = system(@_);
	open STDOUT,"<",$BOUT;
	return ($r == 0);

	#return system(@_) == 1;
#	use Encode qw/from_to find_encoding/;
	$UTF8 = find_encoding('utf-8') unless($UTF8);
	if(open FI,'-|',@_) {
		while(<FI>) {
			from_to($_,'gbk','utf-8');
			print STDERR $UTF8->encode($UTF8->decode($_));
		}
		close FI;
		return 1;
	}
	else {
		print STDERR "Error: $!\n";
		return undef;
	}
}

sub create_link {
	my $OPTS = shift;
	my $target = shift;
	my $link = shift;
	my @prog = (qw/cmd.exe \/c mklink/);
	
	if(!$OPTS) {
		$OPTS={symbold=> 1};
	}

	
	if($OPTS->{symbol} || $OPTS->{file}) {
		print STDERR "Creating symbol link for files";
	}
	elsif($OPTS->{junction}) {
		print STDERR "Creating junction for directories";
		push @prog,'/j';
	}
	elsif($OPTS->{hard}) {
		print STDERR "Creating hard link";
		push @prog,'/h';
	}
	else {#if($OPTS->{symbold}) {
		print STDERR "Creating symbol link for directories";
		push @prog,'/d';
	}
	print STDERR "\n  $link\n  => $target\n";

	return run(@prog,$link,$target);
}

sub junction {
	return &create_link({junction=>1},@_);
	my $target = shift;
	my $junction = shift;
	print STDERR "  Create junction $junction\n   =>$target>\n";
	my @prog = (qw/cmd.exe \/c mklink \/d/);
	return run(@prog,$junction,$target);
}


sub usage {
	Pod::Usage::pod2usage(-verbose=>$1);
}

sub get_basename {
	my $_ = shift;
	s/[\/\\]+$//;
	s/.*[\/\\]+//;
	return $_;
}

sub ms_path {
	my $src = shift;
	my $dst = `cygpath -w  -- "$src"`;
	chomp($dst);
	return $dst;
}


my $failed;
if($OPTS{'target'}) {
	my $DSTD = $OPTS{'target'};
	if(! -d $DSTD) {
		print STDERR "Directory not exist: $DSTD\n";
		exit 2;
	}
	$DSTD = ms_path($DSTD);
	if(!@ARGV) {
		usage();
		exit 1;
	}
	foreach my $src (@ARGV) {
		$OPTS{file} = 1 if(-f $src);

		my $name = get_basename($src);
		$src =~ tr'/'\\';

		$failed = 1 unless(create_link(\%OPTS,$src,$DSTD . "\\" . $name));

		delete $OPTS{file};
	}
}
else {
	my $target = shift;
	my $junction = shift;
	if(!($junction and $target)) {
		usage();
		exit 1;
	}
	if($junction eq '.') {
		$junction = get_basename($target);
	}
	elsif($junction =~ m/\/$/) {
		$junction = catfile($junction,get_basename($target));
	}
	$OPTS{file} = 1 if(-f $target);
	$failed=1 unless(create_link(\%OPTS,ms_path($target),ms_path($junction)));
}
exit 1 if($failed);
exit 0;



__END__

=pod

=head1  NAME

ntfs-junction - PERL script

=head1  SYNOPSIS

ntfs-junction [options] ...

=head1  OPTIONS

=over 12

=item B<--version>

Print version infomation.

=item B<-h>,B<--help>

Print a brief help message and exits.

=item B<--manual>,B<--man>

View application manual

=item B<--edit-me>

Invoke 'editor' against the source

=back

=head1  DESCRIPTION

___DESC___

=head1  CHANGELOG

    2015-03-19 21:50  xiaoranzzz  <xiaoranzzz@MyPlace>
        
        * file created.

=head1  AUTHOR

xiaoranzzz <xiaoranzzz@MyPlace>

=cut

#       vim:filetype=perl

