#!/usr/bin/perl -w
###APPNAME:     parse_proxycn
###APPAUTHOR:   duel
###APPDATE:	2009-01-24 01:42:36
###APPVER:	0.1
###APPDESC:     parse_proxycn	
###APPUSAGE:	
###APPEXAMPLE:	parse_proxycn
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty/;
exit 0 if(help_required($0,@ARGV));
#exit 0 if(help_even_empty($0,@ARGV));

my %proxys;
my $type;
while(<>) {
    chomp;
    if(/\<TD class=\"list\"\>\s*(HTTP|SOCKS)\d*\s*\<\/TD\>/i) {
        $type = $1;
        $type = "PROXY" if(uc($type) eq "HTTP")
    }
    if($type) {
        my @match = $_ =~ /clip\('([\d\.]+:\d+)'\)/g;
        foreach(@match) {
            $proxys{"$type $_"}=1;    
            $type = undef;
        }
    }
}
print join("\n",keys %proxys),"\n";
exit 0;
my @proxys = keys %proxys;
my @pac;
push @pac,"var count=0;\nvar index=0;\nfunction FindProxyForURL(url, host){";
push @pac,"\tvar proxys = new Array();";
push @pac,"\tvar proxys_max = $#proxys;";
foreach my $idx(0 .. $#proxys) {
    push @pac, "\tproxys[" . $idx . "]=\"" . $proxys[$idx] . "\"";
}
push @pac,"\tcount++;\n\tif(count>3){count=0;index++;}\n\tif(index>proxys_max){index=0;}}";
push @pac,"\treturn proxys[index];";
push @pac,"}";

print join("\n",@pac),"\n";


