#!/usr/bin/perl -w
###APPNAME:     ___APPNAME___
###APPAUTHOR:   ___AUTHOR___
###APPDATE:	___DATE___
###APPVER:	0.1
###APPDESC:     ___APPNAME___	
###APPUSAGE:	
###APPEXAMPLE:	___APPNAME___
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty/;
exit 0 if(help_required($0,@ARGV));
#exit 0 if(help_even_empty($0,@ARGV));


