#!/usr/bin/perl -w
###APPNAME:     pl-netcat
###APPAUTHOR:   duel
###APPDATE:	2009-01-06 17:32:15
###APPVER:	0.1
###APPDESC:     pl-netcat a http url
###APPUSAGE:    (url)	
###APPEXAMPLE:	pl-netcat www.google.com
use strict;
use lib $ENV{XR_PERL_MODULE_DIR};
use MyPlace::Script::Usage qw/help_required help_even_empty/;
exit 0 if(help_even_empty($0,@ARGV));

my $url=shift;
$url = "http://$url" unless($url =~ /^http:/i);
use MyPlace::Cache;
use LWP::UserAgent;
use HTTP::Cookies;
use Data::Dumper;

my $cache = MyPlace::Cache->new("pl-netcat");
my @values = $cache->load($url);
if(@values) {
    print @values;
    exit 0;
}
my  $ua = LWP::UserAgent->new;
my $cookie = HTTP::Cookies->new(file => "$ENV{'HOME'}/.lwp_cookies.dat", autosave => 1);
$ua->cookie_jar($cookie);
$ua->agent("Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.3) Gecko/2008092416 Firefox/3.0.3 Firefox/3.0.1");
my $req = HTTP::Request->new(GET => $url);
my $res = $ua->request($req);
if ($res->is_success) {
    print $cache->save($url,$res->content);
    exit 0;
    
}
else {
    print STDERR $res->status_line, "\n";
    exit 1;
}

