#!/usr/bin/perl -w
###APPNAME:     plcp
###APPAUTHOR:   root
###APPDATE:	Fri Sep 21 13:15:05 2007
###APPVER:	0.1
###APPDESC:     copy perl script	
###APPUSAGE:	(source name) (target name)
###APPEXAMPLE:	plcp plcp plcopy
###APPOPTION:	
use strict;
use lib $ENV{XR_PERL_MODULE_DIR};
use MyPlace::Script::ENV qw/$SRC_DIR/;
use MyPlace::Script::Usage qw/help_even_empty/;
exit 0 if help_even_empty($0,@ARGV);
my $srcFile="$SRC_DIR/$ARGV[0].pl";
my $dstFile="$SRC_DIR/$ARGV[1].pl";
system("cp","-vi",$srcFile,$dstFile);
system("sed","-i", "-e", "s/$ARGV[0]/$ARGV[1]/g","$dstFile");





