#!/usr/bin/perl -w
###APPNAME:     plcurl
###APPAUTHOR:   geek
###APPDATE:	Sat Sep 29 13:09:36 2007
###APPVER:	0.1
###APPDESC:	
###APPUSAGE:	
###APPEXAMPLE:	
###APPOPTION:	
use strict;
$ARGV[0]="-h" unless(@ARGV);
foreach(@ARGV){
    exit(system("plhelp",$0,@ARGV)) if($_ eq "-h" || $_ eq "--help");
}


open CURL,"curl " .  join(" ",@ARGV) . " 2>&1|"; 
my $count;
while(<CURL>) {
    $count++;
    print("$count:\n$_\n");
}
close(CURL);
