#!/usr/bin/perl -w
###APPNAME:     plhelp
###APPAUTHOR:   root
###APPDATE:	Fri Sep 21 12:11:45 2007
###APPVER:	0.1
###APPDESC:     format perl script help message	
###APPUSAGE:	(Filename) [Args...]
###APPEXAMPLE:	plhelp "/share/bin/plhelp" 
use strict;
use lib $ENV{XR_PERL_MODULE_DIR};
use MyPlace::Script::Usage qw(/help_required/);

exit 0 if(help_required(@ARGV));
exit 1;








