#!/usr/bin/perl -w
###APPNAME:     plmv
###APPAUTHOR:   xiaoranzzz
###APPDATE:	2009-06-19 16:40:42
###APPVER:	0.1
###APPDESC:     Rename perl script	
###APPUSAGE:	src_name dst_name
###APPEXAMPLE:	plmv plmv plrename
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};
use MyPlace::Script::Usage qw/help_required help_even_empty/;
#exit 0 if(help_required($0,@ARGV));
exit 0 if(help_even_empty($0,@ARGV));

my $fname=shift;
my $nname=shift;
unless($nname) {
    help_even_empty($0);
    exit 0;
}
die("$fname == $nname\n") if($fname eq $nname);

my $PLDIR=$ENV{XR_PERL_SOURCE_DIR};
die("\$XR_PERL_SOURCE_DIR not set or not valid\n") unless(-d $PLDIR);

my $fsrc="$PLDIR/$fname.pl";
my $nsrc="$PLDIR/$nname.pl";

my $SHDIR=$ENV{XR_PERL_BINARY_DIR};
die("\$XR_PERL_BINARY_DIR not set or not valid\n") unless(-d $SHDIR);
my $flnk="$SHDIR/$fname";
my $nlnk="$SHDIR/$nname";

die("$fsrc not exist\n") unless(-f $fsrc);

open FI,"<",$fsrc or die("$!\n");
open FO,">",$nsrc or die("$!\n");
while(<FI>) {
    s/$fname/$nname/g;
    print FO $_;
}
close FI;
close FO;
#system("mv","-v","--",$fsrc,$nsrc);
system("rm","-v","--",$flnk) if(-l $flnk);
system("ln","-vfs",$nsrc,$nlnk);

