#!/usr/bin/perl -w
###APPNAME:     pmfile
###APPAUTHOR:   xiaoranzzz
###APPDATE:	Sun Apr  6 15:07:18 2008
###APPVER:	0.1
###APPDESC:     Create new perl module	
###APPUSAGE:	(moduleName)
###APPEXAMPLE:	pmfile MyPlace::NewModule
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};
use MyPlace::Script::Usage qw/help_even_empty/;
exit 0 if(help_even_empty($0,@ARGV));

my $pm=shift;
my $pn = $pm;
$pn =~ s/::/\//g;
print "$ENV{XR_PERL_MODULE_DIR}/$pn.pm\n";

