#!/usr/bin/perl -w
###APPNAME:     pmnew
###APPAUTHOR:   xiaoranzzz
###APPDATE:	Sun Apr  6 15:07:18 2008
###APPVER:	0.1
###APPDESC:     Create new perl module	
###APPUSAGE:	(moduleName)
###APPEXAMPLE:	pmnew MyPlace::NewModule
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};
use MyPlace::Script::Usage qw/help_even_empty/;
exit 0 if(help_even_empty($0,@ARGV));

my $pm=shift;
my $pn = $pm;
$pn =~ s/::/\//g;
my $fn="$ENV{XR_PERL_MODULE_DIR}/$pn.pm";
my $dn=$fn;
$dn =~ s/\/[^\/]+$/\//;
if(!-d $dn) {
    system("mkdir","-p",$dn) and die("$!\n");
}
exit system("r-vim",$fn) if(-f $fn);

open FO,"|-","r-vim - -c \"file \"$fn\"\"" or die("$!\n");
print FO '#!/usr/bin/perl -w',"\n";
print FO "package $pm;\n";
print FO <<'EOF'
use strict;
use warnings;
BEGIN {
#    sub debug_print {
#        return unless($ENV{XR_PERL_MODULE_DEBUG});
#        print STDERR __PACKAGE__," : ",@_;
#    }
#    &debug_print("BEGIN\n");
    require Exporter;
    our ($VERSION,@ISA,@EXPORT,@EXPORT_OK,%EXPORT_TAGS);
    $VERSION        = 1.00;
    @ISA            = qw(Exporter);
    @EXPORT         = qw();
    @EXPORT_OK      = qw();
}
1;
EOF
;
close FO;

