#!/usr/bin/perl -w
###APPNAME:     png2jpg
###APPAUTHOR:   duel
###APPDATE:	2008-05-16 01:41:05
###APPVER:	0.1
###APPDESC:     convert image format from png to jpg	
###APPUSAGE:	
###APPEXAMPLE:	png2jpg
###APPOPTION:	-d:Delete orignal images
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty/;
exit 0 if(help_even_empty($0,@ARGV));

use MyPlace::Script::Message;

my $delete=shift;
if($delete eq "-d") {
    $delete=1;
}
else {
    unshift @ARGV,$delete;
    $delete=0;
}

sub convert($) {
    my $src=shift;
    my $dst=$src . ".jpg";
    $dst =~ s/\.[^\.]+\.jpg/.jpg/;
    app_message "\"$src\" -> \"$dst\"\n";
    return (system("convert","$src","jpg:$dst") == 0)
}

if($delete) {
    foreach(@ARGV) {
        if(convert($_)) {
            app_message("Unlinking $_\n");
            unlink $_;
        }
    }
}
else {
    foreach(@ARGV) {
        convert($_);
    }
}

