#!/usr/bin/perl -w
###APPNAME:     queue_torrent
###APPAUTHOR:   duel
###APPDATE:	2008-05-16 05:30:04
###APPVER:	0.1
###APPDESC:     queue_torrent	
###APPUSAGE:	
###APPEXAMPLE:	queue_torrent
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty/;
exit 0 if(help_even_empty($0,@ARGV));

my $bak_d="$ENV{HOME}/.myplace";
mkdir $bak_d unless(-d $bak_d);
$bak_d = $bak_d . "/torrents";
mkdir $bak_d unless(-d $bak_d);

my @files;
foreach(@ARGV) {
    if(-f $_) {
        unless($_ =~ /\.torrent$/) {
            my $name = $_ . " - " . time() . ".torrent";
            rename $_, $name;
            $_ = $name;
        }
        print STDERR "\"$_\" enqueued\n";
        push @files,$_;
    }
    else {
        warn "File not exists:\"$_\"\n";
    }
}

my $client=("qbittorrent","transmission","deluge")[2];

system("cp","-v","--",@files,$bak_d);
exec $client,@files;







