#!/usr/bin/perl
use Env qw/OS XAUTHORITY DISPLAY/;
#my @w=qw/notepad++.bat/;
my @w=qw/gvim.exe/;
my @g=qw/gvim -f/;
my @c=qw/vim/;
@g = @c;
my @editor;

if($Env{OS} =~ m/Windows/i) {
	@editor= @w;
    shift @ARGV if(@ARGV and $ARGV[0] eq '-b');
    if(-f "/bin/cygpath.exe") {
        foreach(@ARGV) {
            #die("cygpath $_");
            $_ = `cygpath -w "$_"`;
#            if(m/^\//);
        }
    }
}
elsif($XAUTHORITY or $DISPLAY) {
	@editor= @g;
}
else{
	@editor = @c;
}
print STDERR join(" ",@editor,@ARGV),"\n";
exec @editor,@ARGV;

