#!/usr/bin/perl
use Env qw/OS XAUTHORITY DISPLAY/;
#my @w=qw/notepad++.bat/;

my %EDITORS = (
	windows=>[['gvim.exe'],['vim.exe']],
	cygwin=>[['np.bat'],['np.bat']],
#	cygwin=>[['vim','-p'],['vim','-p']],
	linux=>[['gvim','-p','-f'],['vim','-p']],
);

my $os = 'linux';
my $OSTYPE = $^O;
if(!$OSTYPE) {
	$os = 'windows';
}
elsif($OSTYPE eq 'cygwin') {
	$os = 'cygwin';
}
elsif($OS =~ m/Windows/i) {
	$os = 'windows';
}
else {
	$os = 'linux';
}

my $x = 0;
if($XAUTHORITY or $DISPLAY) {
	$x = 1;
}
my $bg = 0;

my @args;
foreach(@ARGV) {
	if($_ eq '-b') {
		$bg = 1;
	}
	else {
		push @args,$_;
	}
}

my @cmds = @{$EDITORS{$os}->[$x]};
if($cmds[0] and $cmds[0] =~ m/\.(?:exe|bat)$/) {
	if(-f "/bin/cygpath.exe") {
		foreach(@args) {
			$_ = `/bin/cygpath.exe -w "$_"`;
			chomp($_);
		}
	}
}
print STDERR join(" ",@cmds,@args),"\n";
exec @cmds,@args;

