#!/usr/bin/perl -w
###APPNAME:     r-fbset
###APPAUTHOR:   duel
###APPDATE:	Wed May  5 19:26:14 2010
###APPVER:	0.1
###APPDESC:     r-fbset	
###APPUSAGE:	
###APPEXAMPLE:	r-fbset
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty/;
exit 0 if(help_required($0,@ARGV));
#exit 0 if(help_even_empty($0,@ARGV));

my $app="fbset";

exec($app) unless(@ARGV);

my ($xres,$yres,$depth,$rate) = qw/1024 768 16 60/;
my @args;
foreach(@ARGV) {
    if($_ =~ /^(\d+)[xX](\d+)$/) {
        $xres = $1;
        $yres = $2;
    }
    elsif($_ =~ /^(\d+)[xX](\d+)-(\d+)$/) {
        $xres = $1;
        $yres = $2;
        $depth = $3;
    }
    elsif($_ =~ /^(\d+)[xX](\d+)-(\d+)\@(\d+)$/) {
        $xres = $1;
        $yres = $2;
        $depth = $3;
        $rate = $4;
    }
    else {
        push @args,$_;
    }
}
@args = ("-xres",$xres,"-yres",$yres,"-depth",$depth,@args);
print STDERR join(" ",($app,@args)),"\n";
exec($app,@args);

