#!/usr/bin/perl -w
###APPNAME:     r-vncviewer
###APPAUTHOR:   duel
###APPDATE:	Wed May  5 20:28:54 2010
###APPVER:	0.1
###APPDESC:     r-vncviewer	
###APPUSAGE:	
###APPEXAMPLE:	r-vncviewer
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty/;
exit 0 if(help_required($0,@ARGV));
#exit 0 if(help_even_empty($0,@ARGV));

