#!/usr/bin/perl -w
###APPNAME:     rotate13
###APPAUTHOR:   duel
###APPDATE:	2008-09-19 01:43:10
###APPVER:	0.1
###APPDESC:     rotate13	
###APPUSAGE:	
###APPEXAMPLE:	rotate13
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty/;
exit 0 if(help_required($0,@ARGV));
#exit 0 if(help_even_empty($0,@ARGV));

while(<>) {
    tr/abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/nopqrstuvwxyzabcdefghijklmNOPQRSTUVWXYZABCDEFGHIJKLM/;
    print $_;
}

