#!/usr/bin/env perl
use strict;
require v5.8.0;
our $VERSION = 'v0.1';

BEGIN
{
    our $PROGRAM_DIR = $ENV{XR_PERL_SOURCE_DIR};
    unless($PROGRAM_DIR) {
        $PROGRAM_DIR = $0;
        $PROGRAM_DIR =~ s/[^\/\\]+$//;
        $PROGRAM_DIR =~ s/\/+$//;
        $PROGRAM_DIR = "." unless($PROGRAM_DIR);
    }
    unshift @INC, 
        map "$PROGRAM_DIR/$_",qw{modules lib ../modules ..lib};
}

my %OPTS;
my @OPTIONS = qw/help|h|? version|ver edit-me manual|man bz2 gz verbose|v/;

if(@ARGV)
{
    require Getopt::Long;
    require MyPlace::Usage;
    Getopt::Long::GetOptions(\%OPTS,@OPTIONS);
    MyPlace::Usage::Process(\%OPTS,$VERSION);
}
else
{
    require MyPlace::Usage;
    MyPlace::Usage::PrintHelp();
    exit 0;
}

use Cwd qw/getcwd/;
my $cwd = getcwd;

sub run {
    my $exit = system(@_);
    die("fatal error: $! while executing [",join(" ",@_),"]\n") if($exit);
    return 1;
}

my $dumpcmd = $OPTS{verbose} ? 'svnadmin dump' : 'svnadmin dump -q';

sub svndump {
	my $local = shift;
	my $name = shift;
	print STDERR "$local ...\n";
	my $rev;
	my $last;
	if(open FI,"-|",'svn','info','file://' . $local) {
		foreach(<FI>) {
			if(m/^\s*Last Changed Rev:\s*(\d+)/) {
				$rev = $1;
			}
			elsif(m/^\s*Last Changed Date:\s*(\d+)-(\d+)-(\d+)/) {
				$last = "$1$2$3";
			}
		}
		close FI;
		my $dst = $name;
		$dst = $dst . "_r$rev" if($rev);
#		$dst = $dst . "_$last" if($last);
		$dst = $dst . ".svndump";
		print STDERR "\t-> $dst\n";
		if(!run("$dumpcmd \"$local\" >\"$dst\"")) {
			print STDERR "failed\n";
			return undef;
		}
		if($OPTS{bz2}) {
			run(qw/bzip2 -9v/,$dst);
		}
		elsif($OPTS{gz}) {
			run(qw/gzip -9v/,$dst);
		}
	}
	else {
		print STDERR "error: not a subversion repository\n";
	}
}

foreach my $local (@ARGV) {
	if(! -d $local) {
		print STDERR "directory not exist: $local\n";
		next;
	}
	$local =~ s/\/+$//;
	my $name = $local;
	$name =~ s/\//_/g;
	$name =~ s/svn_|_svn//g;
	$local = "$cwd/$local" unless($local =~ m/^\//);
	svndump($local,$name);
}

__END__

=pod

=head1  NAME

svndump - PERL script

=head1  SYNOPSIS

svndump [options] ...

=head1  OPTIONS

=over 12

=item B<--version>

Print version infomation.

=item B<-h>,B<--help>

Print a brief help message and exits.

=item B<--manual>,B<--man>

View application manual

=item B<--edit-me>

Invoke 'editor' against the source

=back

=head1  DESCRIPTION

___DESC___

=head1  CHANGELOG

    2010-11-21 03:48  xiaoranzzz  <xiaoranzzz@myplace.hell>
        
        * file created.

=head1  AUTHOR

xiaoranzzz <xiaoranzzz@myplace.hell>

=cut

#       vim:filetype=perl
