#!/usr/bin/perl -w
# $Id$
use strict;
require v5.8.0;
our $VERSION = 'v0.1';

BEGIN
{
    our $PROGRAM_DIR = $ENV{XR_PERL_SOURCE_DIR};
    unless($PROGRAM_DIR) {
        $PROGRAM_DIR = $0;
        $PROGRAM_DIR =~ s/[^\/\\]+$//;
        $PROGRAM_DIR =~ s/\/+$//;
        $PROGRAM_DIR = "." unless($PROGRAM_DIR);
    }
    unshift @INC, 
        map "$PROGRAM_DIR/$_",qw{modules lib ../modules ..lib};
}

my %OPTS;
my @OPTIONS = qw/help|h|? version|ver edit-me manual|man/;

if(@ARGV)
{
    require Getopt::Long;
    require MyPlace::Usage;
    Getopt::Long::GetOptions(\%OPTS,@OPTIONS);
    MyPlace::Usage::Process(\%OPTS,$VERSION);
}
else
{
    require MyPlace::Usage;
    MyPlace::Usage::PrintHelp();
    exit 0;
}

sub run {
    my $exit = system(@_);
    die("fatal error: $! while executing [",join(" ",@_),"]\n") if($exit);
    return 1;
}
sub create_repo {
    my $DEST = shift;
    if(! -d $DEST) {
        print STDERR "creating local repository $DEST...\n";
        run(qw/svnadmin create/,$DEST);
        my $hook = "$DEST/hooks/pre-revprop-change";
        print STDERR "creating pre-revprop-change hook in $DEST...\n";
        open FO,'>',$hook or die("fatal error\n");
        print FO "#!/bin/sh\nexit 0\n";
        close FO;
        run(qw/chmod a+x/,$hook);
    }
}


my $action = shift;
my $dst = shift;
unless($dst) {
    $dst = $action;
    $action = 'load';
}

if($action eq 'load') {
    create_repo($dst);
    run('svnadmin','load',$dst);
}
else {
    run('svnadmin',$action,$dst,@ARGV);
}



__END__

=pod

=head1  NAME

svndump - PERL script

=head1  SYNOPSIS

svndump [options] ...

=head1  OPTIONS

=over 12

=item B<--version>

Print version infomation.

=item B<-h>,B<--help>

Print a brief help message and exits.

=item B<--manual>,B<--man>

View application manual

=item B<--edit-me>

Invoke 'editor' against the source

=back

=head1  DESCRIPTION

___DESC___

=head1  CHANGELOG

    2010-11-21 03:48  xiaoranzzz  <xiaoranzzz@myplace.hell>
        
        * file created.

=head1  AUTHOR

xiaoranzzz <xiaoranzzz@myplace.hell>

=cut

#       vim:filetype=perl
