#!/usr/bin/perl -w
###APPNAME:     test_glob
###APPAUTHOR:   xiaoranzzz
###APPDATE:	2009-06-22 19:19:58
###APPVER:	0.1
###APPDESC:     test_glob	
###APPUSAGE:	
###APPEXAMPLE:	test_glob
###APPOPTION:	
use strict;

use File::Glob qw/:glob/;

foreach(@ARGV) {
	print "***$_***:\n";
	print $_,"\n" foreach(glob($_));
}
