#!/usr/bin/perl -w
###APPNAME:     unzipfolder
###APPAUTHOR:   xiaoranzzz
###APPDATE:	Wed Oct 17 07:51:57 2007
###APPVER:	0.1
###APPDESC:     Unzip file to directory
###APPUSAGE:	[OPTIONS] (zipfiles...)
###APPOPTION:	-d:Delete file after successful unzipped|-e:Ext Name(will be cut to make directory)
###APPEXAMPLE:  unzipfolder -d -e v2.zbook notev2.zbook abcdefgv2.zbook
use strict;
use Getopt::Std;
use lib $ENV{XR_PERL_MODULE_DIR};
use MyPlace::Script::Usage qw/help_even_empty format_help/;

exit 0 if(help_even_empty($0,@ARGV));

my $OptFlag='hde:';
my %OPT;
exit(format_help $0) unless(getopts($OptFlag,\%OPT));

my $do_unlink = $OPT{d} ? 1 : 0;
my $ext = $OPT{e} ? $OPT{e} : "";

my @files;
foreach(@ARGV) {
    if(-r $_) {
        push(@files,$_);
    }
    else {
        print STDERR ("File not accessable:\"$_\"\n");
    }
}
die("Nothing to do\n") unless(@files);

sub resetLine {
    print "\r" . " "x50;
    print "\r";
}
sub dosys {
    return (system(@_)==0);
}


require MyPlace::Filename;

foreach my $idx(0 .. $#files) {
    my $src = $files[$idx];
    my $bn;
    if($ext) {
        $bn = MyPlace::Filename::get_filename($src);
        $bn =~ s/$ext$//;
    }
    else {
        $bn=MyPlace::Filename::get_basename($src);
    }
    if(dosys "unzip","-qo",$src,"-d",$bn) {
        resetLine;
        print("[",$idx+1,"/",$#files+1,"] \"$src\"->\"$bn\" [Done]\n");
        if($do_unlink) {
            print("Deleting \"$src\" ...");
            if(unlink $src) {
                resetLine;
                print("Deleting \"$src\" [OK]\n");
            }
            else {
                resetLine;
                print("Deleting \"$src\" [Failed]\n");
            }
        }
    }
    else {
        resetLine;
        print("\"$src\"->\"$bn\" [Failed]\n");
    }
}



