#!/usr/bin/perl -w
###APPNAME:     urlrule_source
###APPAUTHOR:   duel
###APPDATE:	Mon Mar 24 06:25:31 2008
###APPVER:	0.1
###APPDESC:     dump urlrule result	
###APPUSAGE:	URL [0-5]
###APPEXAMPLE:	urlrule_source http://www.sina.com.cn 0
use strict;
use Data::Dumper;

use lib $ENV{XR_PERL_MODULE_DIR};
use MyPlace::Script::Usage qw/help_even_empty/;
exit 0 if(help_even_empty($0,@ARGV));

use MyPlace::URLRule;


my %rule = %{parse_rule(@ARGV)};
my $source = $rule{"source"};
print $source,"\n";



