#!/usr/bin/perl -w
###APPNAME:     urlrule_action
###APPAUTHOR:   duel
###APPDATE:	Mon Mar 24 06:25:31 2008
###APPVER:	0.1
###APPDESC:     apply rule for URL,and perform action	
###APPUSAGE:	urlrule_action URL [0-5] [action args...]
###APPEXAMPLE:	urlrule_action http://www.sina.com.cn 0 cat
use strict;
use utf8;

use MyPlace::Script::Usage qw/help_required help_even_empty/;
exit 0 if(help_required($0,@ARGV));

use MyPlace::Script::Message;
use MyPlace::URLRule;
use MyPlace::ReEnterable;
use Cwd qw/getcwd/;

urlrule_set_callback('process_passdown',\&process_passdown);

my $RESUME_FILE = '.urlrule_resume';
my $phnd = MyPlace::ReEnterable->new('main');
my $cwd = getcwd();
$SIG{INT} = \&sig_killed;

sub process_passdown {
    my ($count,@passdown) = urlrule_get_passdown(@_);
    my $cwd = getcwd();
    if($count) {
        app_message("Get $count rules to pass down\n");
    }
    else {
        return undef;
    }
    foreach(@passdown) {
        $phnd->push($cwd,'load_rule',@{$_});
    }
}

sub load_rule {
    my $cwd = getcwd();
    my ($status1,$rule,$result) = urlrule_process_args(@_);
    if($status1) {
        my($status2,$pass_count,@passdown)
            = urlrule_process_result($rule,$result);
        if($status2 and $pass_count and $pass_count>0) {
            my $cwd = getcwd();
            foreach(@passdown) {
                $phnd->push($cwd,'load_rule',@{$_});
            }
        }
    }
    chdir $cwd;
}

sub sig_killed {
    app_message("saving remained tasks...\n");
    if($phnd->{lastStack}) {
        $phnd->unshift(@{$phnd->{lastStack}});
    }
    chdir($cwd) if($cwd);
    $phnd->saveToFile($RESUME_FILE);
    app_message($phnd->length," tasks saved to $RESUME_FILE\n");
    exit 1;
}

if(@ARGV) {
    $phnd->push($cwd,'load_rule',undef,@ARGV);
}
else {
    $phnd->loadFromFile($RESUME_FILE);
}
while(my $tasks = $phnd->length) {
    app_error("[$tasks] tasks remained\n");
    my @this = $phnd->peek();
    if(@this) {
        my $wdir = shift @this;
        my $cmd = shift @this;
#        app_warning("rule       -  @this\n");
#        app_warning("directory  -  $wdir\n");
    }
    $phnd->run();
}
app_message "All tasks completed.\n";
unlink $RESUME_FILE if(-f $RESUME_FILE);
exit 0;
