#!/usr/bin/perl -w
###APPNAME:     urlrule_dump
###APPAUTHOR:   duel
###APPDATE:	Mon Mar 24 06:25:31 2008
###APPVER:	0.1
###APPDESC:     dump urlrule result	
###APPUSAGE:	URL [0-5]
###APPEXAMPLE:	urlrule_dump http://www.sina.com.cn 0
use strict;
use Data::Dumper;

use lib $ENV{XR_PERL_MODULE_DIR};
use MyPlace::Script::Usage qw/help_even_empty/;
exit 0 if(help_even_empty($0,@ARGV));

use MyPlace::Script::Message;
use MyPlace::URLRule qw/parse_rule apply_rule/;
use Data::Dumper;

my $rule = parse_rule(@ARGV);
print STDERR Data::Dumper->Dump([$rule],['*rule']);

my $result = apply_rule($rule);
if($result and ref $result) {
        print STDERR Data::Dumper->Dump([$result],['result']);
        exit 0;
}
else {
    app_error("Error: result contians nothing\n");
    exit 1;
}

