#!/usr/bin/perl -w
###APPNAME:     urlrule_dump
###APPAUTHOR:   duel
###APPDATE:	Mon Mar 24 06:25:31 2008
###APPVER:	0.1
###APPDESC:     dump urlrule result	
###APPUSAGE:	URL [0-5]
###APPEXAMPLE:	urlrule_dump http://www.sina.com.cn 0
use strict;
use Data::Dumper;

use lib $ENV{XR_PERL_MODULE_DIR};
use MyPlace::Script::Usage qw/help_even_empty/;
exit 0 if(help_even_empty($0,@ARGV));

use MyPlace::Script::Message;
use MyPlace::URLRule;


my %rule = %{parse_rule(@ARGV)};

my $url=$rule{"url"};
my $source = $rule{"source"};
my $level = $rule{"level"};
my $msghd = "";

#app_message("%Rule :\n");
print STDERR Data::Dumper->Dump([\%rule],["*rule"]);

#unless(-f $source) {
#    app_abort("File not found: $source\n");
#}

#do $source;

app_message($msghd , "Level $level>>","For \"$url\"\n");
app_message($msghd , "Level $level>>","Found rule: \"$source\"\n");
app_message($msghd , "Level $level>>","Applying it ...\n");
my ($status,$result)=execute_rule(%rule);
if($status) {
    print STDERR Data::Dumper->Dump([$result],["*result"]);
}
else {
    app_message("Error:$result\n");
}



