#!/usr/bin/perl -w
###APPNAME:     urlrule_action
###APPAUTHOR:   duel
###APPDATE:	Mon Mar 24 06:25:31 2008
###APPVER:	0.1
###APPDESC:     apply rule for URL,and perform action	
###APPUSAGE:	urlrule_action URL [0-5] [action args...]
###APPEXAMPLE:	urlrule_action http://www.sina.com.cn 0 cat
use strict;

use lib $ENV{XR_PERL_MODULE_DIR};
use MyPlace::Script::Usage qw/help_required help_even_empty/;
exit 0 if(help_even_empty($0,@ARGV));

use MyPlace::URLRule;
use Cwd qw/getcwd/;
my %rule = %{parse_rule(@ARGV)};
use Data::Dumper;print STDERR Data::Dumper->Dump([\%rule],["%rule"]);
    if(!-f $rule{source}) {
        print STDERR "File not found: $rule{source}\n";
        exit 1;
    }
    else {
        open FI,"<",$rule{source} or die("$!\n");
        print STDOUT <FI>;
        close FI;
    }


