#!/usr/bin/perl -w
use strict;
my $action = uc($ARGV[0]) if(@ARGV);
if($action and $action =~ /^(?:DOWNLOAD|DUMP|ECHO)$/) {
        shift @ARGV;
        exec('urlrule_task',$action,@ARGV);
        exit 0;
}

my $TASK_DATABASE   = "DATABASE.URL";
open FO,">>","urlrule_database.log";
print FO scalar(localtime),": urlrule_database ",(map "\"$_\" ",@ARGV),"\n";
close FO;

if($action and $action =~ /^(?:ADD)$/) {
        push @ARGV,'newly',unless ($ARGV[$#ARGV] eq 'newly');
}
exec 'r-config','-f',$TASK_DATABASE,@ARGV;
