#!/usr/bin/perl -w
###APPNAME:     urlrule_new
###APPAUTHOR:   xiaoranzzz
###APPDATE:	Sat Mar 22 22:56:33 2008
###APPVER:	0.1
###APPDESC:     create new url rule	
###APPUSAGE:	URL [0-5]
###APPEXAMPLE:	urlrule_new http://www.shuku.net/novels/gulong/bianlang/bianlang.html 2
###APPOPTION:	
use strict;
use lib $ENV{XR_PERL_MODULE_DIR};
use MyPlace::Script::Usage qw/help_even_empty/;

exit 0 if(help_even_empty($0,@ARGV));

use MyPlace::ColorPrint;
use MyPlace::URLRule qw/parse_rule/;

my %rule = %{parse_rule(@ARGV)};
my $url=$rule{url};
my $level=$rule{level};
my $source=$rule{source};


if(-f $source) {
    app_message("Rule for $url exists,opened for editing instead\n");
    system("r-vim \"$source\"");
    exit 0;
}

my $date=localtime();
open VIMED,"|-","r-vim -c 'file $source' - ";
print VIMED <<"HEAD";
#!/usr/bin/perl -w
#$url
#$date
use strict;


HEAD

print VIMED <<'FUNC';

=method1
sub apply_rule {
 return (
       '#use quick parse'=>1,
       'data_exp'=>undef,
       'data_map'=>undef,
       'pass_exp'=>undef,
       'pass_map'=>undef,
       'pass_name_map'=>undef,
       'pages_exp'=>undef,
       'pages_map'=>undef,
       'pages_pre'=>undef,
       'pages_suf'=>undef,
       'pages_start'=>undef,
       'title_exp'=>undef,
       'title_map'=>undef,
       'charset'=>undef
 );
}
=cut

=method2
use MyPlace::Curl;
#use MyPlace::HTML;

sub _process {
    my ($url,$rule,$html) = @_;
    my $title = undef;
    my @data;
    my @pass_data;
    #my @html = split(/\n/,$html);
    return (
        count=>scalar(@data),
        data=>[@data],
        pass_count=>scalar(@pass_data),
        pass_data=>[@pass_data],
        base=>$url,
        no_subdir=>1,
        work_dir=>$title,
    );
}

sub apply_rule {
    my $url = shift(@_);
    my $rule = shift(@_);
    my $http = MyPlace::Curl->new();
    my (undef,$html) = $http->get($url);
    return &_process($url,$rule,$html,@_);
}
=cut

1;
FUNC
print VIMED <<'USAGE';

__END__

#================================================================
# apply_rule will be called with ($RuleBase,%Rule),the result returned have these meaning:
# $result{base}          : Base url to build the full url
# $result{work_dir}      : Working directory (will be created if not exists)
# $result{data}          : Data array extracted from url,will be passed to $result{action}(see followed)
# $result{action}        : Command which the $result{data} will be piped to,can be overrided
# $result{pipeto}        : Same as action,Command which the $result{data} will be piped to,can be overrided
# $result{hook}          : Hook action,function process_data will be called
# $result{no_subdir}     : Do not create sub directories
# $result{pass_data}     : Data array which will be passed to next level of urlrule
# $result{pass_name}     : Names of each $result{pass_data}
# $result{pass_arg}      : Additional arguments to be passed to next level of urlrule
# urlrule_quick_parse($url,$rule,$data_exp,$data_map,$pass_exp,$pass_map,$charset)
# urlrule_parse_data($url,$rule,$data_exp,$data_map,$charset)
# urlrule_parse_pass_data($url,$rule,$pass_exp,$pass_map,$charset)
# 
# $result{same_level}    : Keep same rule level for passing down
# $result{level}         : Specify rule level for passing down
#================================================================

#       vim:filetype=perl
USAGE


close VIMED;

if(-f "$source" and ! -x "$source") {
    chmod 0775,$source; 
}
exit 0;

