#!/usr/bin/perl -w
use strict;
if(@ARGV) {
    my $action = uc($ARGV[0]);
    if($action =~ /^(?:DOWNLOAD|DUMP|ECHO)$/) {
        shift @ARGV;
        exec('urlrule_task',$action,@ARGV);
        exit 0;
    }
    elsif($action =~ /^(?:ADD)$/) {
        push @ARGV,'newly',unless ($ARGV[$#ARGV] eq 'newly');
    }
}

my $TASK_DATABASE   = "DATABASE.URL";
exec 'r-config','-f',$TASK_DATABASE,@ARGV;
