#!/usr/bin/perl -w
###APPNAME:     webdisk_download
###APPAUTHOR:   duel
###APPDATE:	2009-01-27 06:57:22
###APPVER:	0.1
###APPDESC:     webdisk_download	
###APPUSAGE:	
###APPEXAMPLE:	webdisk_download
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty/;
exit 0 if(help_required($0,@ARGV));
#exit 0 if(help_even_empty($0,@ARGV));

my @urls = @ARGV;
unless(@urls) {
    while(<STDIN>) {
        chomp;
        push @urls,$_;
    }
}
die("Error:no urls specified!\n") unless(@urls);
foreach(@urls) {
    if(/rayfile.com/) {
        system("rayfile_download",$_);
    }
    elsif(/namipan.com/) {
        system("namipan_download",$_);
    }
    else {
        print STDERR "Error:Webdisk type not supported\n";
    }
}
