#!/usr/bin/perl -w
###APPNAME:     wget_dir
###APPAUTHOR:   xiaoranzzz
###APPDATE:	2009-06-19 18:14:23
###APPVER:	0.1
###APPDESC:     download a directory,using wget
###APPUSAGE:	[URL]
###APPEXAMPLE:	wget_dir http://mirror.href.com/thestarman/asm/mbr/index.html
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};
use MyPlace::Script::Usage qw/help_required help_even_empty/;
exit 0 if(help_even_empty($0,@ARGV));

my $url=$ARGV[0];
my $dir=$ARGV[1];
$dir="./" unless($dir);
sub count_match {
    my @count = $_[0] =~ m/$_[1]/g;
    return scalar(@count);
}
my $slashcount= count_match($url,'/') - count_match($url,'//')*2 - 1;
#die($slashcount,"\n");

mkdir $dir unless(-d $dir);
chdir $dir or die("$!\n");

my $cmds="wget -e robots=off --progress=bar -x -N -np -nH -v --cut-dirs=$slashcount -r -l 0 \"$url\"";
if(open FO,">:utf8","wget.log") {
    print FO scalar(localtime) . ":\n$0 " . join(" ",@ARGV) . "\n" ;
    print FO scalar(localtime) . ":\n $cmds\n";
    print FO "#"x76,"\n";
    close FO;
}
system $cmds . ' 2>&1 | tee -a wget.log';

