#!/usr/bin/perl -w
###APPNAME:     wineapp
###APPAUTHOR:   xiaoranzzz
###APPDATE:	2009-06-26 20:30:28
###APPVER:	0.1
###APPDESC:     wineapp	
###APPUSAGE:	
###APPEXAMPLE:	wineapp
###APPOPTION:	
use strict;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_required help_even_empty/;
#exit 0 if(help_required($0,@ARGV));
exit 0 if(help_even_empty($0,@ARGV));

my $appdir="/myplace/wine/public/apps";
my $name = shift;
$name = "$name.exe" unless($name =~ /\.(:?dll|exe)$/i);
my @props;
print STDERR "find $appdir -iname $name\n";
open FI,"-|","find",$appdir,"-iname", $name  or die("$!\n");
while(<FI>) {
	chomp;
	push @props,$_;
}
close FI;
my $select;
if(@props>1) {
	my $idx;
	print ":@props program matched:\n";
	foreach(@props) {
		$idx++;
		printf "[%03d]:%s\n",$idx,$_;
	}
	print "Please select (1-$idx):";
	$idx = <STDIN>;
	chomp $idx;
	if($idx =~ /^[0-9]+$/ and $idx>=1 and $idx<=@props) {
		$select = $props[$idx-1];
	}
	else {
		print "Invalid choice.\n";
		exit 1;
	}
}
else {
	$select = $props[0];
}

if($select) {
	if($select =~ /\.dll$/) {
		print STDERR "regsvr32 $select\n";
		exec "regsvr32",$select;
	}
	else {
		print STDERR "cn_wine $select\n";
		exec "cn_wine","$select";
	}
}
exit 0;


