#!/usr/bin/perl -w
###APPNAME:     xr-pl-new
###APPAUTHOR:   xiaoranzzz
###APPDATE:	Wed Apr  2 21:05:11 2008
###APPVER:	0.1
###APPDESC:     xr-pl-new	
###APPUSAGE:	
###APPEXAMPLE:	xr-pl-new
###APPOPTION:	
use strict;
use lib $ENV{XR_PERL_MODULE_DIR};

use MyPlace::Script::Usage qw/help_even_empty/;
exit 0 if(help_even_empty($0,@ARGV));

