#!/usr/bin/perl 
###APPNAME:     xrzReader
###APPAUTHOR:   xiaoranzzz
###APPDATE:	2008-09-09 05:33:17
###APPVER:	0.1
###APPDESC:     extend zim for supporting directories browsing.
###APPUSAGE:	
###APPOPTION:	
use strict;
no warnings;

#ENV variable MUST be defined somewhere,
#FOR perl to search modules from,
#OR nothing will work
unshift @INC,$ENV{XR_PERL_MODULE_DIR};
my $zim = `which zim`;
chomp($zim) if($zim);
die("Can't not found zim,it maybe not installed!\n") unless($zim);
require $zim;


